import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono, Orbitron, Inter } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import NavBar from "@/components/NavBar";
import { Suspense } from "react";
import SearchVehiclesLink from "@/components/SearchVehiclesLink";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${inter.variable} antialiased`}
      >
        <AuthProvider>
          <header className="flex items-center justify-between px-6 py-4 border-b bg-white shadow-sm">
            <Link
              href="/"
              className="flex items-center gap-3 hover:opacity-80 transition-opacity"
            >
              <h1
                className="text-4xl font-bold tracking-tight leading-none text-red-600 underline"
                style={{ fontFamily: "var(--font-orbitron)" }}
              >
                M8 Cars              </h1>
            </Link>
            <div className="flex items-center gap-3">
              <Suspense
                fallback={
                  <a
                    href="/data-list"
                    className="px-4 py-2 text-sm font-medium bg-primary text-primary-foreground rounded-md hover:opacity-90 transition-opacity"
                  >
                    Search Vehicles
                  </a>
                }
              >
                <SearchVehiclesLink className="px-4 py-2 text-sm font-medium bg-primary text-primary-foreground rounded-md hover:opacity-90 transition-opacity" />
              </Suspense>
              <NavBar />
            </div>
          </header>
          <div className="min-h-[calc(100vh-73px)] flex flex-col">
            <main className="flex-1">{children}</main>
            <footer className="border-t bg-gray-900 text-gray-400 text-sm">
              <div className="max-w-6xl mx-auto px-6 py-8 flex flex-col sm:flex-row items-center justify-between gap-4">
                <span
                  className="text-xl font-bold text-red-500"
                  style={{ fontFamily: "var(--font-orbitron)" }}
                >
                  M8 Cars
                </span>
                <p className="text-xs text-gray-500">&copy; {new Date().getFullYear()} M8 Cars. All rights reserved.</p>
                <nav className="flex gap-4 text-xs">
                  <Link href="/data-list" className="hover:text-white transition-colors">Browse Cars</Link>
                  <Link href="/new-vehicle" className="hover:text-white transition-colors">Sell Your Car</Link>
                </nav>
              </div>
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
