import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import NavBar from "@/components/NavBar";
import { Suspense } from "react";
import SearchVehiclesLink from "@/components/SearchVehiclesLink";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} antialiased`}
      >
        <AuthProvider>
          <header className="flex items-center justify-between px-6 py-4 border-b bg-white shadow-sm">
            <Link
              href="/"
              className="flex items-center gap-3 hover:opacity-80 transition-opacity"
            >
              <h1
                className="text-4xl font-bold tracking-tight leading-none text-red-600 underline"
                style={{ fontFamily: "var(--font-orbitron)" }}
              >
                M8 Cars
              </h1>
            </Link>
            <div className="flex items-center gap-3">
              <Suspense
                fallback={
                  <a
                    href="/data-list"
                    className="px-4 py-2 text-sm font-medium bg-primary text-primary-foreground rounded-md hover:opacity-90 transition-opacity"
                  >
                    Search Vehicles
                  </a>
                }
              >
                <SearchVehiclesLink className="px-4 py-2 text-sm font-medium bg-primary text-primary-foreground rounded-md hover:opacity-90 transition-opacity" />
              </Suspense>
              <NavBar />
            </div>
          </header>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
